Repository uplus-3/frontend, pull requests merged in 2022-08, with the labels that each got.

#2 [FEAT] readme 수정
  README.md
Labels: :sparkles: Feature, :memo: Docs

#5 [FEAT] api 커스텀
  src/lib/api/client.js
Labels: :sparkles: Feature

#7 [FEAT} 테마 설정
  src/App.js
  src/theme/theme.js
Labels: :sparkles: Feature

#8 [FEAT] 라우터 및 레이아웃 설정
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/common/Navbar.js
  src/index.js
  src/pages/MainPage.js
  src/pages/SearchResultPage.js
  src/pages/order/DeviceOrderHistoryPage.js
  src/pages/order/DeviceOrderPage.js
  src/pages/product/DeviceDetailPage.js
  src/pages/product/DeviceListPage.js
  src/router.js
Labels: :sparkles: Feature

#12 [FEAT] 라우터 경로 변경 및 레이아웃 설정 (#9)
  src/common/Navbar.js
  src/layout/MainLayout.js
  src/pages/NotFoundPage.js
  src/router.js
Labels: :sparkles: Feature

#15 :sparkles: 폰트 설정 및 글로벌 스타일 설정 (#14)
  public/favicon.ico
  src/App.js
  src/assets/fonts/LGSmHaB.ttf
  src/assets/fonts/LGSmHaL.ttf
  src/assets/fonts/LGSmHaR.ttf
  src/assets/fonts/LGSmHaSB.ttf
  src/assets/images/logo_uplus.png
  src/components/common/Navbar.js
  src/index.css
  src/layout/MainLayout.js
  src/theme/theme.js
Labels: :sparkles: Feature

#19 ✨ 헤더 레이아웃 구성 및 검색창 배치
  package-lock.json
  package.json
  src/components/common/Navbar.js
  src/components/common/NavbarContent.js
  src/components/common/RoundBtn.js
  src/layout/MainLayout.js
  src/lib/hooks/useInput.js
  yarn.lock
Labels: :sparkles: Feature

#20 :sparkles: 최근검색어 저장 및 검색 페이지 이동기능 생성
  src/components/common/SearchBar.js
  src/pages/MainPage.js
Labels: :sparkles: Feature

#22 Feat/i18
  src/assets/images/SM-F721N-purple-0.jpg
  src/components/common/SearchBar.js
  src/components/device/DeviceList.js
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListFilter.js
  src/components/device/DeviceListHeader.js
  src/components/device/DeviceListItem.js
  src/index.js
  src/pages/product/DeviceListPage.js
  src/reset.css
  src/theme/theme.js
  yarn.lock
Labels: :sparkles: Feature

#24 ✨ 상품리스트 필터 label과 checkbox 연동 및 정렬 탭 구현 (#23)
  src/components/device/DeviceList.js
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListFilter.js
  src/components/device/DeviceListHeader.js
  src/pages/product/DeviceListPage.js
Labels: :sparkles: Feature

#27 ✨ 검색기능 구체화 및 헤더 레이아웃 조정
  src/components/common/Navbar.js
  src/components/common/SearchBar.js
  src/router.js
Labels: :sparkles: Feature

#29 ✨ 리덕스 환경 설정 (#26)
  package.json
  src/components/common/SearchBar.js
  src/components/device/DeviceList.js
  src/index.js
  src/modules/actions/devicesSlice.js
  src/modules/index.js
  src/modules/sagas/devicesSaga.js
  src/modules/store.js
  src/pages/product/DeviceListPage.js
  yarn.lock
Labels: :sparkles: Feature

#31 ✨상품리스트 필터 리덕스 연결
  src/assets/images/SM-F721N-blue-0.jpg
  src/assets/images/SM-F721N-gold-0.jpg
  src/assets/images/SM-F721N-graphite-0.jpg
  src/components/device/DeviceList.js
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListFilter.js
  src/components/device/DeviceListHeader.js
  src/components/device/DeviceListItem.js
  src/modules/actions/devicesSlice.js
  src/pages/product/DeviceListPage.js
Labels: :sparkles: Feature

#34 :sparkles: 상품 상세페이지 레이아웃
  src/components/common/Navbar.js
  src/components/device/DeviceItemImage.js
  src/components/device/DeviceItemInfo.js
  src/components/modal/PriceCompareModal.js
  src/layout/MainLayout.js
  src/pages/MainPage.js
  src/pages/product/DeviceDetailPage.js
Labels: :sparkles: Feature

#39 [FEAT] 상품리스트 필터 및 정렬 적용시 쿼리스트링 변경
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListFilter.js
  src/components/device/DeviceListHeader.js
  src/modules/actions/devicesSlice.js
  src/modules/sagas/devicesSaga.js
  src/pages/product/DeviceListPage.js
Labels: :sparkles: Feature

#41 :sparkles: 주문하기 페이지 레이아웃 구성 (#36)
  src/components/common/SquareBtn.js
  src/components/device/DeviceItemInfo.js
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
  src/lib/utils.js
  src/pages/order/DeviceOrderPage.js
Labels: :sparkles: Feature

#42 [BUG] 상품 리스트에서 뒤로가기 시 필터 적용 (#40)
  src/components/device/DeviceListFilter.js
  src/components/device/DeviceListHeader.js
  src/modules/actions/devicesSlice.js
  src/pages/product/DeviceListPage.js
Labels: :bug: Bug

#44 ✨ 상품 비교하기 탭 레이아웃
  package.json
  src/components/device/compare/DeviceCompareItem.js
  src/components/device/compare/DeviceCompareTab.js
  src/pages/product/DeviceListPage.js
  yarn.lock
Labels: :sparkles: Feature

#46 ✨ 주문하기 레이아웃 수정
  package-lock.json
  package.json
  public/index.html
  src/components/common/Navbar.js
  src/components/device/DeviceItemInfo.js
  src/components/modal/DaumPostCodeModal.js
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
  src/pages/order/DeviceOrderPage.js
  yarn.lock
Labels: :sparkles: Feature

#50 :sparkles: 상품 가격 비교하기 레이아웃 구현
  package-lock.json
  src/components/device/DeviceItemInfo.js
  src/components/modal/PriceCompareModal.js
  yarn.lock
Labels: :sparkles: Feature

#51 [FEAT] 상품 리스트 페이지에서 상품 클릭 시 상세페이지로 라우터 적용 (#48)
  package.json
  src/components/device/DeviceList.js
  src/components/device/DeviceListItem.js
  src/modules/actions/devicesSlice.js
  yarn.lock
Labels: :sparkles: Feature

#52 ✨ 검색창 레이아웃 수정하기
  src/components/common/SearchBar.js
Labels: :sparkles: Feature

#53 [FEAT] 비교하기 상세페이지 모달 레이아웃
  src/components/device/compare/DeviceCompareInfo.js
  src/components/device/compare/DeviceCompareInfoPlan.js
  src/components/device/compare/DeviceCompareInfoPrice.js
  src/components/device/compare/DeviceCompareInfoPriceItem.js
  src/components/device/compare/DeviceCompareInfoSpec.js
  src/components/device/compare/DeviceCompareItem.js
  src/components/device/compare/DeviceCompareItemSelect.js
  src/components/device/compare/DeviceCompareItemSelector.js
  src/components/device/compare/DeviceCompareTab.js
  src/components/modal/DeviceCompareModal.js
  src/theme/theme.js
Labels: :sparkles: Feature

#55 [FEAT] 장바구니 페이지 레아아웃 구현 (#54)
  src/components/cart/CartLIstItem.js
  src/components/cart/CartList.js
  src/components/cart/CartListEmpty.js
  src/components/common/RoundBtn.js
  src/pages/cart/CartListPage.js
  src/router.js
Labels: :sparkles: Feature

#57 [FEAT] 장바구니 아이콘 추가
  src/components/common/Navbar.js
  src/components/device/DeviceListItem.js
Labels: :sparkles: Feature

#59 ✨ 주문하기 페이지 분기처리 및 다듬기
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/assets/images/icon-kakao.png
  src/components/common/RoundBtn.js
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
  src/lib/api/client.js
  src/lib/api/device.js
  src/lib/api/order.js
  src/lib/hooks/useAlert.js
  src/pages/order/DeviceOrderPage.js
  yarn.lock
Labels: :sparkles: Feature

#60 [FEAT] 상품리스트 상단으로 가는 버튼 추가
  package.json
  src/components/cart/CartLIstItem.js
  src/components/common/ScrollTopBtn.js
  src/components/device/compare/DeviceCompareItem.js
  src/pages/product/DeviceListPage.js
  yarn.lock
Labels: :sparkles: Feature

#65 :sparkles: 검색 데이터 연결
  src/components/common/SearchBar.js
Labels: :sparkles: Feature
