Repository uplus-3/frontend, pull requests merged in 2022-09, with the labels that each got.

#66 [FEAT] 상품 리스트 데이터 연결
  package-lock.json
  src/components/device/DeviceList.js
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListFilter.js
  src/components/device/DeviceListHeader.js
  src/components/device/DeviceListItem.js
  src/components/order/OrderReceipt.js
  src/lib/api/device.js
  src/lib/api/plan.js
  src/modules/actions/devicesSlice.js
  src/modules/actions/loadingSlice.js
  src/modules/actions/planSlice.js
  src/modules/index.js
  src/modules/sagas/devicesSaga.js
  src/modules/sagas/planSaga.js
  src/pages/product/DeviceListPage.js
  src/router.js
Labels: :sparkles: Feature

#74 ✨ 검색결과 페이지 구현
  src/components/device/search/DeviceSearchList.js
  src/components/device/search/DeviceSearchListItem.js
  src/pages/SearchResultPage.js
Labels: :sparkles: Feature

#83 [feat] 주문조회 페이지 구현
  .env
  package.json
  src/components/common/Navbar.js
  src/components/common/SearchBar.js
  src/components/device/DeviceItemImage.js
  src/components/device/DeviceItemInfo.js
  src/components/modal/PriceCompareModal.js
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
  src/components/order/OrderSearchForm.js
  src/lib/api/client.js
  src/lib/api/order.js
  src/pages/order/DeviceOrderHistoryPage.js
  src/pages/order/DeviceOrderPage.js
  src/pages/order/DeviceOrderSearchInputPage.js
  src/pages/product/DeviceDetailPage.js
  src/router.js
Labels: :sparkles: Feature

#77 [REFACTOR] 상품 리스트 페이지 api 연동 수정
  src/components/device/DeviceList.js
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListItem.js
  src/components/device/compare/DeviceCompareItem.js
  src/lib/api/test.js
  src/modules/actions/devicesSlice.js
  src/modules/actions/errorSlice.js
  src/modules/index.js
  src/modules/sagas/devicesSaga.js
  src/pages/product/DeviceListPage.js
Labels: :recycle: Refactor

#82 ♻️ 검색 결과 수 수정, 검색 결과 없을 때 문구 추가
  src/pages/SearchResultPage.js
Labels: :recycle: Refactor

#84 ✨ 주문하기 페이지 데이터 연동
  .env
  .gitignore
  package.json
  src/App.js
  src/components/cart/CartLIstItem.js
  src/components/cart/CartList.js
  src/components/cart/CartListEmpty.js
  src/components/common/Navbar.js
  src/components/common/SearchBar.js
  src/components/device/DeviceItemInfo.js
  src/components/device/DeviceListHeader.js
  src/components/device/DeviceListItem.js
  src/components/device/compare/DeviceCompareInfo.js
  src/components/device/compare/DeviceCompareInfoPrice.js
  src/components/device/compare/DeviceCompareInfoPriceItem.js
  src/components/device/compare/DeviceCompareItem.js
  src/components/device/compare/DeviceCompareTab.js
  src/components/modal/DeviceCompareModal.js
  src/components/modal/PriceCompareModal.js
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
  src/lib/api/cart.js
  src/lib/api/client.js
  src/lib/api/device.js
  src/lib/hooks/useCart.js
  src/modules/actions/planSlice.js
  src/modules/sagas/planSaga.js
  src/pages/cart/CartListPage.js
  src/pages/order/DeviceOrderPage.js
  src/pages/product/DeviceDetailPage.js
  src/pages/product/DeviceListPage.js
  yarn.lock
Labels: :sparkles: Feature, :recycle: Refactor

#86 [FEAT] 비교하기 모달 기능 구현
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListFilter.js
  src/components/device/compare/DeviceCompareInfo.js
  src/components/device/compare/DeviceCompareInfoContent.js
  src/components/device/compare/DeviceCompareInfoPlan.js
  src/components/device/compare/DeviceCompareInfoPlanItem.js
  src/components/device/compare/DeviceCompareInfoPrice.js
  src/components/device/compare/DeviceCompareInfoPriceItem.js
  src/components/device/compare/DeviceCompareInfoSpec.js
  src/components/device/compare/DeviceCompareItem.js
  src/components/device/compare/DeviceCompareItemSelect.js
  src/components/device/compare/DeviceCompareItemSelector.js
  src/components/modal/DeviceCompareModal.js
  src/index.js
  src/lib/api/device.js
  src/modules/actions/devicesSlice.js
  src/modules/sagas/devicesSaga.js
  src/pages/product/DeviceListPage.js
Labels: :sparkles: Feature

#90 :sparkles: 장바구니 기능 연결 및 자잘한 에러 수정
  src/components/cart/CartListEmpty.js
  src/components/common/Navbar.js
  src/components/common/NavbarContent.js
  src/components/common/SearchBar.js
  src/components/device/DeviceItemInfo.js
  src/components/device/DeviceListItem.js
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
  src/lib/api/order.js
  src/lib/hooks/useCart.js
  src/pages/order/DeviceOrderPage.js
  src/pages/product/DeviceDetailPage.js
  src/router.js
Labels: :sparkles: Feature

#93 :sparkles: 주문 조회, 수정, 취소 구현 및 수정, api method 변경 및 라우터 추가
  package-lock.json
  src/components/order/OrderSearchForm.js
  src/lib/api/order.js
  src/pages/order/DeviceOrderAddressUpdatePage.js
  src/pages/order/DeviceOrderHistoryPage.js
  src/pages/order/DeviceOrderSearchInputPage.js
  src/router.js
Labels: :sparkles: Feature

#91 [FEAT] 출시 예정 단말기 리스트에 출력
  .env
  src/components/device/DeviceList.js
  src/components/device/DeviceListFileterContents.js
  src/components/device/DeviceListHeader.js
  src/components/device/launching/LaunchingDeviceListItem.js
  src/components/modal/LaunchingDeviceDetailModal.js
  src/index.js
  src/lib/api/device.js
  src/modules/actions/devicesSlice.js
  src/modules/sagas/devicesSaga.js
  src/pages/product/DeviceListPage.js
Labels: :sparkles: Feature

#96 [FEAT] 상품 리스트 loading, error 처리 및 Error 컴포넌트 생성
  src/components/common/Error.js
  src/components/common/Loading.js
Labels: :sparkles: Feature

#98 [REFACTOR] 출시 예정 단말기 출력 관련 코드 수정
  src/components/device/DeviceList.js
  src/modules/actions/devicesSlice.js
Labels: :recycle: Refactor

#99 [FEAT] 상품 리스트 색상별 품절 적용
  src/components/device/DeviceListItem.js
Labels: :sparkles: Feature

#101 [BUG] 상품 비교하기 모달에서 상품 클릭시 상세페이지 렌더링 오류
  src/components/device/compare/DeviceCompareItem.js
  src/components/modal/DeviceCompareModal.js
Labels: :bug: Bug

#107 🐛 검색결과가 네트워크 타입에 따라 바뀌지 않는 오류 수정
  src/pages/SearchResultPage.js
Labels: :bug: Bug

#112 :sparkles: 주문조회 입력폼 하드코딩 내용 제거, .env 수정
  .env
  src/components/order/OrderSearchForm.js
  src/pages/order/DeviceOrderHistoryPage.js
Labels: :sparkles: Feature

#111 ✨ 검색결과 페이지 로딩, 에러 추가
  src/pages/SearchResultPage.js
Labels: :sparkles: Feature

#114 [REFACTOR] 상품리스트 검색 search -> regex로 변경 (#113)
  src/modules/actions/devicesSlice.js
Labels: :recycle: Refactor

#116 :recycle: 장바구니 구현방식 변경 (#115)
  src/lib/api/cart.js
  src/lib/hooks/useCart.js
Labels: :recycle: Refactor

#119 :bug: 주문페이지 가격 변경
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
Labels: :bug: Bug

#105 [BUG] 상품 리스트 페이지에서 5g, 4g 이동 시, header option 초기화
  src/components/device/DeviceListHeader.js
  src/pages/product/DeviceListPage.js
Labels: :bug: Bug

#123 :recycle: 에러처리 및 코드정리
  src/components/common/Navbar.js
  src/components/common/SearchBar.js
  src/components/device/DeviceItemInfo.js
  src/components/order/OrderReceipt.js
  src/lib/hooks/useCart.js
  src/pages/MainPage.js
  src/pages/NotFoundPage.js
  src/pages/order/DeviceOrderPage.js
  src/pages/product/DeviceDetailPage.js
Labels: :sparkles: Feature, :recycle: Refactor

#121 [REFACTOR] 상품 리스트 태그 애니메이션 적용 (#120)
  src/components/device/DeviceListItem.js
  src/components/device/compare/DeviceCompareItemSelector.js
Labels: :recycle: Refactor

#124 [REFACTOR] web title 설정
  package.json
  src/components/device/DeviceList.js
  src/index.js
  src/pages/MainPage.js
  src/pages/NotFoundPage.js
  src/pages/SearchResultPage.js
  src/pages/cart/CartListPage.js
  src/pages/order/DeviceOrderAddressUpdatePage.js
  src/pages/order/DeviceOrderHistoryPage.js
  src/pages/order/DeviceOrderPage.js
  src/pages/order/DeviceOrderSearchInputPage.js
  src/pages/product/DeviceDetailPage.js
  src/pages/product/DeviceListPage.js
  yarn.lock
Labels: :recycle: Refactor

#131 :sparkle: 장바구니 쿠키 설정 변경
  src/components/device/DeviceItemInfo.js
  src/lib/hooks/useCart.js
  src/modules/actions/planSlice.js
Labels: :recycle: Refactor

#132 :recycle: secure 제거
  src/lib/hooks/useCart.js
Labels: :recycle: Refactor

#133 [BUG] 비교하기 모달 상품 리스트 중복 제거
  src/modules/actions/devicesSlice.js
Labels: :bug: Bug

#134 :recycle: 카트 개수 0개일 때 분기처리
  src/pages/cart/CartListPage.js
Labels: :recycle: Refactor

#137 ♻️ searchbar 기본값 변경
  src/components/common/SearchBar.js
Labels: :recycle: Refactor

#143 :recycle: 불필요한 코드 삭제 (#142)
  src/App.css
  src/App.js
  src/components/common/NavbarContent.js
  src/components/common/SearchBar.js
  src/components/device/DeviceListFilter.js
  src/components/device/DeviceListHeader.js
  src/components/device/DeviceListItem.js
  src/components/device/compare/DeviceCompareInfo.js
  src/components/device/compare/DeviceCompareInfoPlan.js
  src/components/device/compare/DeviceCompareInfoPlanItem.js
  src/components/device/compare/DeviceCompareInfoPrice.js
  src/components/device/compare/DeviceCompareItemSelector.js
  src/components/device/search/DeviceSearchList.js
  src/components/modal/DaumPostCodeModal.js
  src/components/modal/PriceCompareModal.js
  src/components/order/OrderForm.js
  src/components/order/OrderReceipt.js
  src/components/order/OrderSearchForm.js
  src/index.css
  src/lib/api/client.js
  src/lib/api/device.js
  src/lib/hooks/useAlert.js
  src/lib/hooks/useCart.js
  src/lib/hooks/useInput.js
  src/lib/utils.js
  src/modules/actions/planSlice.js
  src/modules/sagas/devicesSaga.js
  src/modules/sagas/planSaga.js
  src/pages/SearchResultPage.js
  src/pages/cart/CartListPage.js
  src/pages/order/DeviceOrderAddressUpdatePage.js
  src/pages/order/DeviceOrderHistoryPage.js
  src/pages/order/DeviceOrderPage.js
  src/pages/order/DeviceOrderSearchInputPage.js
Labels: :recycle: Refactor

#145 [hotfix] 월 납부금액 합산 로직 수정
  src/components/device/DeviceItemInfo.js
Labels: :bug: Bug

#146 [hotfix] 월 납부금액 합산 오류 디버깅
  src/components/device/DeviceItemInfo.js
Labels: :bug: Bug

#147 [hotfix] 가격정보 수정
  src/pages/product/DeviceDetailPage.js
Labels: :bug: Bug
